In [1]:
import numpy as np

# --- Các giá trị so sánh cặp bạn đã cung cấp ---
# Đặt tên biến rõ ràng hơn một chút (ví dụ: pb_vs_nd thay vì phobien_vs_nhipdo)
# Giá trị thể hiện mức độ quan trọng của tiêu chí bên trái SO VỚI tiêu chí bên phải
pb_vs_nd = 3
pb_vs_nl = 7
pb_vs_nh = 9
pb_vs_cx = 5
nd_vs_nl = 2
nd_vs_nh = 4
nd_vs_cx = 6
nl_vs_nh = 3
nl_vs_cx = 2
nh_vs_cx = 5

# --- Danh sách các tiêu chí ---
criteria = ["phobien", "nhipdo", "nangluong", "nhay", "camxuc"]
n = len(criteria)

# --- Tạo ma trận rỗng ---
# Sử dụng numpy để dễ dàng xử lý số học, đặc biệt là số thập phân
comparison_matrix = np.zeros((n, n))

# --- Điền các giá trị vào ma trận ---

# 1. Đường chéo chính luôn là 1 (so sánh tiêu chí với chính nó)
for i in range(n):
    comparison_matrix[i, i] = 1.0

# 2. Điền các giá trị bạn đã cung cấp vào nửa trên của ma trận
#    (Sử dụng chỉ số dựa trên thứ tự trong list 'criteria')
#    phobien=0, nhipdo=1, nangluong=2, nhay=3, camxuc=4

comparison_matrix[0, 1] = pb_vs_nd
comparison_matrix[0, 2] = pb_vs_nl
comparison_matrix[0, 3] = pb_vs_nh
comparison_matrix[0, 4] = pb_vs_cx

comparison_matrix[1, 2] = nd_vs_nl
comparison_matrix[1, 3] = nd_vs_nh
comparison_matrix[1, 4] = nd_vs_cx

comparison_matrix[2, 3] = nl_vs_nh
comparison_matrix[2, 4] = nl_vs_cx

comparison_matrix[3, 4] = nh_vs_cx

# 3. Điền các giá trị nghịch đảo vào nửa dưới của ma trận
#    Nếu A so với B là x, thì B so với A là 1/x
for i in range(n):
    for j in range(i + 1, n): # Chỉ lặp qua nửa trên
        if comparison_matrix[i, j] != 0: # Kiểm tra để tránh chia cho 0 nếu có lỗi
            comparison_matrix[j, i] = 1.0 / comparison_matrix[i, j]
        else:
            # Xử lý trường hợp giá trị 0 nếu cần, ở đây các giá trị đều dương
            pass 

# --- In ma trận ra màn hình cho giống hình ảnh ---

# Hàm để định dạng số (hiển thị dạng phân số nếu có thể)
def format_number(num):
    if num == 1.0:
        return "1"
    if num > 1 and num.is_integer():
         return str(int(num))
    # Kiểm tra các giá trị nghịch đảo phổ biến
    if np.isclose(num, 1/2): return "1/2"
    if np.isclose(num, 1/3): return "1/3"
    if np.isclose(num, 1/4): return "1/4"
    if np.isclose(num, 1/5): return "1/5"
    if np.isclose(num, 1/6): return "1/6"
    if np.isclose(num, 1/7): return "1/7"
    if np.isclose(num, 1/8): return "1/8"
    if np.isclose(num, 1/9): return "1/9"
    # Nếu không phải, hiển thị dạng số thập phân (ví dụ: 2 chữ số)
    return f"{num:.2f}"

# In tiêu đề cột
print(f"{'':<10}" + "".join([f"{c:<10}" for c in criteria]))
print("-" * (10 * (n + 1))) # Dòng kẻ ngang

# In các hàng của ma trận
for i in range(n):
    row_str = f"{criteria[i]:<10}" # Tên tiêu chí hàng
    for j in range(n):
        formatted_num = format_number(comparison_matrix[i, j])
        row_str += f"{formatted_num:<10}" # Giá trị đã định dạng
    print(row_str)

          phobien   nhipdo    nangluong nhay      camxuc    
------------------------------------------------------------
phobien   1         3         7         9         5         
nhipdo    1/3       1         2         4         6         
nangluong 1/7       1/2       1         3         2         
nhay      1/9       1/4       1/3       1         5         
camxuc    1/5       1/6       1/2       1/5       1         


In [2]:
import numpy as np # Import lại phòng trường hợp cell mới chưa import

# --- Giả định rằng 'comparison_matrix' và 'criteria' đã tồn tại từ cell trước ---
# comparison_matrix là một NumPy array (n x n) chứa các giá trị float
# criteria là một list chứa tên các tiêu chí

# Kiểm tra xem biến có tồn tại không (tùy chọn, để tránh lỗi nếu chạy cell này độc lập)
if 'comparison_matrix' not in globals() or 'criteria' not in globals():
    print("Lỗi: Vui lòng chạy cell tạo 'comparison_matrix' và 'criteria' trước.")
else:
    n = len(criteria) # Lấy lại kích thước ma trận

    # --- 1. Tính tổng các cột ---
    # axis=0 nghĩa là tính tổng theo chiều dọc (các cột)
    column_sums = comparison_matrix.sum(axis=0)

    # --- 2. In lại ma trận và thêm hàng SUM ---

    # Điều chỉnh độ rộng cột nếu cần cho tên tiêu chí dài
    col_width = 18
    print("\n--- Ma trận So Sánh với Tổng Cột ---")

    # In tiêu đề cột
    header = f"{'':<{col_width}}" + "".join([f"{c:<{col_width}}" for c in criteria])
    print(header)
    print("-" * len(header)) # Dòng kẻ ngang

    # In các hàng của ma trận (định dạng float .2f)
    for i in range(n):
        row_str = f"{criteria[i]:<{col_width}}" # Tên tiêu chí hàng
        for j in range(n):
            # Các giá trị đã là float, chỉ cần định dạng khi in
            formatted_num = f"{comparison_matrix[i, j]:.2f}"
            row_str += f"{formatted_num:<{col_width}}" # Giá trị đã định dạng
        print(row_str)

    # In dòng kẻ phân cách trước hàng SUM
    print("-" * len(header))

    # In hàng SUM (định dạng tổng với độ chính xác cao hơn)
    sum_row_str = f"{'SUM':<{col_width}}"
    for total in column_sums:
        # Định dạng tổng với nhiều chữ số thập phân hơn để giống hình
        formatted_sum = f"{total:.2f}"
        sum_row_str += f"{formatted_sum:<{col_width}}"
    print(sum_row_str)


--- Ma trận So Sánh với Tổng Cột ---
                  phobien           nhipdo            nangluong         nhay              camxuc            
------------------------------------------------------------------------------------------------------------
phobien           1.00              3.00              7.00              9.00              5.00              
nhipdo            0.33              1.00              2.00              4.00              6.00              
nangluong         0.14              0.50              1.00              3.00              2.00              
nhay              0.11              0.25              0.33              1.00              5.00              
camxuc            0.20              0.17              0.50              0.20              1.00              
------------------------------------------------------------------------------------------------------------
SUM               1.79              4.92              10.83             17.20             

In [3]:
import numpy as np # Import lại phòng trường hợp cell mới chưa import

# --- Giả định 'comparison_matrix', 'column_sums', và 'criteria' đã tồn tại ---

# Kiểm tra biến (tùy chọn)
if 'comparison_matrix' not in globals() or 'column_sums' not in globals() or 'criteria' not in globals():
    print("Lỗi: Vui lòng chạy các cell tính toán 'comparison_matrix' và 'column_sums' trước.")
else:
    n = len(criteria) # Lấy lại kích thước

    # --- 1. Chuẩn hóa ma trận ---
    # Chia từng phần tử của ma trận gốc cho tổng của cột tương ứng.
    # NumPy cho phép chia ma trận cho một mảng (áp dụng theo cột) một cách dễ dàng.
    normalized_matrix = comparison_matrix / column_sums

    # --- 2. In ma trận đã chuẩn hóa ---
    col_width = 18 # Giữ nguyên hoặc điều chỉnh độ rộng cột
    decimal_places = 4 # Số chữ số thập phân theo hình ảnh

    print("\n--- Ma trận So Sánh Đã Chuẩn Hóa (Normalized Pair-wise Matrix) ---")
    print("(Giá trị ô / Tổng cột tương ứng)")

    # In tiêu đề cột
    header = f"{'':<{col_width}}" + "".join([f"{c:<{col_width}}" for c in criteria])
    print(header)
    print("-" * len(header)) # Dòng kẻ ngang

    # In các hàng của ma trận chuẩn hóa
    for i in range(n):
        row_str = f"{criteria[i]:<{col_width}}" # Tên tiêu chí hàng
        for j in range(n):
            # Định dạng số float với số chữ số thập phân mong muốn
            formatted_num = f"{normalized_matrix[i, j]:.{decimal_places}f}"
            row_str += f"{formatted_num:<{col_width}}" # Giá trị đã định dạng
        print(row_str)

    # (Không cần in hàng SUM cho ma trận chuẩn hóa này)


--- Ma trận So Sánh Đã Chuẩn Hóa (Normalized Pair-wise Matrix) ---
(Giá trị ô / Tổng cột tương ứng)
                  phobien           nhipdo            nangluong         nhay              camxuc            
------------------------------------------------------------------------------------------------------------
phobien           0.5595            0.6102            0.6462            0.5233            0.2632            
nhipdo            0.1865            0.2034            0.1846            0.2326            0.3158            
nangluong         0.0799            0.1017            0.0923            0.1744            0.1053            
nhay              0.0622            0.0508            0.0308            0.0581            0.2632            
camxuc            0.1119            0.0339            0.0462            0.0116            0.0526            


In [4]:
import numpy as np # Import lại phòng trường hợp cell mới chưa import

# --- Giả định 'normalized_matrix' và 'criteria' đã tồn tại ---

# Kiểm tra biến (tùy chọn)
if 'normalized_matrix' not in globals() or 'criteria' not in globals():
    print("Lỗi: Vui lòng chạy cell tính toán 'normalized_matrix' trước.")
else:
    n = len(criteria) # Lấy lại kích thước

    # --- 1. Tính trọng số tiêu chí (Criteria Weights) ---
    # Tính trung bình cộng của mỗi hàng trong ma trận chuẩn hóa
    # axis=1 nghĩa là tính trung bình theo chiều ngang (các hàng)
    criteria_weights = normalized_matrix.mean(axis=1)

    # --- 2. In ma trận chuẩn hóa kèm cột trọng số ---
    col_width = 18 # Độ rộng cột
    decimal_places = 4 # Số chữ số thập phân

    print("\n--- Tính Trọng Số Ưu Tiên cho Các Tiêu Chí ---")
    print("(Trung bình các giá trị theo hàng của ma trận chuẩn hóa)")

    # In tiêu đề cột, thêm cột "Criteria Weights"
    header_criteria = "".join([f"{c:<{col_width}}" for c in criteria])
    header = f"{'':<{col_width}}{header_criteria}{'Criteria Weights':<{col_width}}"
    print(header)
    print("-" * len(header)) # Dòng kẻ ngang

    # In các hàng của ma trận chuẩn hóa và cột trọng số
    for i in range(n):
        row_str = f"{criteria[i]:<{col_width}}" # Tên tiêu chí hàng
        # In các giá trị từ ma trận chuẩn hóa
        for j in range(n):
            formatted_num = f"{normalized_matrix[i, j]:.{decimal_places}f}"
            row_str += f"{formatted_num:<{col_width}}"
        # In trọng số tương ứng ở cột cuối
        formatted_weight = f"{criteria_weights[i]:.{decimal_places}f}"
        row_str += f"{formatted_weight:<{col_width}}"
        print(row_str)

    # (Tùy chọn) In tổng của các trọng số để kiểm tra (nên gần bằng 1)
    print("-" * len(header))
    sum_weights_check = f"{'Sum Check:':<{col_width * (n+1)}}{criteria_weights.sum():.{decimal_places}f}"
    print(sum_weights_check)


# Bạn có thể lưu lại vector trọng số này để sử dụng sau
# priority_vector = criteria_weights
# print("\nVector trọng số ưu tiên (Priority Vector):")
# print(priority_vector)


--- Tính Trọng Số Ưu Tiên cho Các Tiêu Chí ---
(Trung bình các giá trị theo hàng của ma trận chuẩn hóa)
                  phobien           nhipdo            nangluong         nhay              camxuc            Criteria Weights  
------------------------------------------------------------------------------------------------------------------------------
phobien           0.5595            0.6102            0.6462            0.5233            0.2632            0.5204            
nhipdo            0.1865            0.2034            0.1846            0.2326            0.3158            0.2246            
nangluong         0.0799            0.1017            0.0923            0.1744            0.1053            0.1107            
nhay              0.0622            0.0508            0.0308            0.0581            0.2632            0.0930            
camxuc            0.1119            0.0339            0.0462            0.0116            0.0526            0.0512            
------

In [5]:
import numpy as np # Import lại phòng trường hợp cell mới chưa import

# --- Giả định các biến cần thiết đã tồn tại từ các cell trước ---
# comparison_matrix, criteria_weights, criteria
# weighted_sum_vector = comparison_matrix @ criteria_weights (Tính lại nếu chưa có)
# consistency_vector = weighted_sum_vector / criteria_weights (Tính lại nếu chưa có)

# Kiểm tra biến (tùy chọn)
required_vars = ['comparison_matrix', 'criteria_weights', 'criteria']
if not all(v in globals() for v in required_vars):
    print("Lỗi: Vui lòng chạy các cell tính toán các biến cần thiết trước.")
else:
    n = len(criteria)

    # --- 1. Tính lại các vector cần thiết (để đảm bảo chúng có sẵn) ---
    # Weighted Sum Vector
    weighted_sum_vector = comparison_matrix @ criteria_weights
    # Consistency Vector (tương ứng cột 'Consistency Rate' trong hình)
    consistency_vector = weighted_sum_vector / criteria_weights

    # --- 2. In bảng theo định dạng yêu cầu (tập trung 3 cột cuối) ---
    col_width = 18  # Điều chỉnh độ rộng cột nếu cần
    decimals_wsv = 4
    decimals_weights = 4
    decimals_cr = 8 # Cho cột cuối nhiều chữ số thập phân hơn

    print("\n--- Bảng Tính Vector Nhất Quán ---")
    # (Lưu ý: 5 cột đầu trong hình không được tái tạo do cách tính không rõ ràng)

    # In tiêu đề cột
    header_labels = ["Weight Sum Value", "Criteria Weights", "Consistency Rate"]
    header = f"{'':<{col_width}}" + "".join([f"{label:<{col_width}}" for label in header_labels])
    print(header)
    print("-" * len(header)) # Dòng kẻ ngang

    # In các hàng dữ liệu
    for i in range(n):
        row_str = f"{criteria[i]:<{col_width}}" # Tên tiêu chí hàng
        # Thêm giá trị từ các vector đã tính
        row_str += f"{weighted_sum_vector[i]:<{col_width}.{decimals_wsv}f}"
        row_str += f"{criteria_weights[i]:<{col_width}.{decimals_weights}f}"
        row_str += f"{consistency_vector[i]:<{col_width}.{decimals_cr}f}"
        print(row_str)

    # In lại kết quả Lambda Max để tham khảo (trung bình của cột Consistency Rate)
    lambda_max = np.mean(consistency_vector)
    print("-" * len(header))
    


--- Bảng Tính Vector Nhất Quán ---
                  Weight Sum Value  Criteria Weights  Consistency Rate  
------------------------------------------------------------------------
phobien           3.0626            0.5204            5.88450197        
nhipdo            1.2990            0.2246            5.78444979        
nangluong         0.6789            0.1107            6.13145702        
nhay              0.5001            0.0930            5.37654827        
camxuc            0.2667            0.0512            5.20515975        
------------------------------------------------------------------------


In [6]:
import numpy as np
import pandas as pd # Sử dụng pandas để dễ dàng sắp xếp và hiển thị

# --- Giả định 'criteria_weights' và 'criteria' đã tồn tại ---

# Kiểm tra biến (tùy chọn)
if 'criteria_weights' not in globals() or 'criteria' not in globals():
    print("Lỗi: Vui lòng chạy cell tính toán 'criteria_weights' trước.")
else:
    n = len(criteria)

    # --- 1. Tạo DataFrame để dễ dàng xử lý và xếp hạng ---
    # Kết hợp tên tiêu chí và trọng số thành một cấu trúc dữ liệu
    df_weights = pd.DataFrame({
        'Tiêu chí': criteria,
        'Criteria Weights': criteria_weights
    })

    # --- 2. Tính toán và thêm cột Rank ---
    # Sắp xếp DataFrame theo 'Criteria Weights' giảm dần
    # Sau đó tạo cột 'Rank' dựa trên thứ tự mới (bắt đầu từ 1)
    # .rank(method='first', ascending=False) sẽ gán hạng 1 cho giá trị cao nhất
    df_weights['Rank'] = df_weights['Criteria Weights'].rank(method='dense', ascending=False).astype(int)

    # Sắp xếp lại theo rank để hiển thị (tùy chọn, nếu muốn thứ tự như hình)
    # df_weights = df_weights.sort_values(by='Rank')
    # Hoặc giữ nguyên thứ tự ban đầu nếu muốn
    df_weights = df_weights.sort_index()


    # --- 3. In bảng kết quả ---
    col_width_criteria = 20 # Điều chỉnh độ rộng cột
    col_width_weights = 18
    col_width_rank = 5
    decimal_places = 4

    print("\n--- Trọng Số và Xếp Hạng Các Tiêu Chí ---")

    # In tiêu đề
    header = f"{'':<{col_width_criteria}}{'Criteria Weights':<{col_width_weights}}{'Rank':<{col_width_rank}}"
    print(header)
    print("-" * len(header))

    # In từng hàng từ DataFrame
    for index, row in df_weights.iterrows():
        print(f"{row['Tiêu chí']:<{col_width_criteria}}{row['Criteria Weights']:<{col_width_weights}.{decimal_places}f}{row['Rank']:<{col_width_rank}}")

    # Bạn cũng có thể chỉ cần in DataFrame trực tiếp nếu không cần định dạng tùy chỉnh
    # print("\nBảng DataFrame (dễ xem hơn trong Jupyter):")
    # display(df_weights[['Tiêu chí', 'Criteria Weights', 'Rank']].set_index('Tiêu chí')) # display() hoạt động tốt trong jupyter


--- Trọng Số và Xếp Hạng Các Tiêu Chí ---
                    Criteria Weights  Rank 
-------------------------------------------
phobien             0.5204            1    
nhipdo              0.2246            2    
nangluong           0.1107            3    
nhay                0.0930            4    
camxuc              0.0512            5    


In [7]:
df = pd.read_csv('/kaggle/input/hhtrq-data-song/spotify_songs.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32833 entries, 0 to 32832
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   track_id                  32833 non-null  object 
 1   track_name                32828 non-null  object 
 2   track_artist              32828 non-null  object 
 3   track_popularity          32833 non-null  int64  
 4   track_album_id            32833 non-null  object 
 5   track_album_name          32828 non-null  object 
 6   track_album_release_date  32833 non-null  object 
 7   playlist_name             32833 non-null  object 
 8   playlist_id               32833 non-null  object 
 9   playlist_genre            32833 non-null  object 
 10  playlist_subgenre         32833 non-null  object 
 11  danceability              32833 non-null  float64
 12  energy                    32833 non-null  float64
 13  key                       32833 non-null  int64  
 14  loudne

In [8]:
df = df[['track_name','track_popularity','danceability','energy','valence','tempo']]
df

track_name  track_popularity  \
0      I Don't Care (with Justin Bieber) - Loud Luxur...                66   
1                        Memories - Dillon Francis Remix                67   
2                        All the Time - Don Diablo Remix                70   
3                      Call You Mine - Keanu Silva Remix                60   
4                Someone You Loved - Future Humans Remix                69   
...                                                  ...               ...   
32828               City Of Lights - Official Radio Edit                42   
32829                Closer - Sultan & Ned Shepard Remix                20   
32830                       Sweet Surrender - Radio Edit                14   
32831                     Only For You - Maor Levi Remix                15   
32832                             Typhoon - Original Mix                27   

       danceability  energy  valence    tempo  
0             0.748   0.916   0.5180  122.036  
1             0.726   0.815   0.6930   99.972  
2             0.675   0.931   0.6130  124.008  
3             0.718   0.930   0.2770  121.956  
4             0.650   0.833   0.7250  123.976  
...             ...     ...      ...      ...  
32828         0.428   0.922   0.2100  128.170  
32829         0.522   0.786   0.4000  128.041  
32830         0.529   0.821   0.4360  127.989  
32831         0.626   0.888   0.3080  128.008  
32832         0.603   0.884   0.0894  127.984  

[32833 rows x 6 columns]

In [9]:
import pandas as pd
import numpy as np
import io # Để đọc dữ liệu dạng chuỗi như file


num_songs_to_compare = 4
if len(df) < num_songs_to_compare:
    print(f"Cảnh báo: Chỉ có {len(df)} bài hát trong dữ liệu, sử dụng tất cả.")
    num_songs_to_compare = len(df)

selected_songs = df.head(num_songs_to_compare)

# --- Tạo định danh ngắn gọn cho bài hát (giống BH1, BH2...) ---
song_ids = [f"BH{i+1}" for i in range(num_songs_to_compare)]
# Lưu tên gốc để tham khảo nếu cần
original_song_names = selected_songs['track_name'].tolist()

# --- Lấy giá trị 'track_popularity' của các bài hát đã chọn ---
popularities = selected_songs['track_popularity'].values

# --- Tạo ma trận so sánh cặp cho tiêu chí 'Mức độ phổ biến' ---
n_songs = len(popularities)
comparison_matrix_popularity = np.zeros((n_songs, n_songs), dtype=float)

for i in range(n_songs):
    for j in range(n_songs):
        if popularities[j] == 0:
             # Xử lý trường hợp chia cho 0 (ví dụ: gán giá trị rất lớn hoặc báo lỗi)
             # Ở đây, ta tạm gán giá trị lớn nếu popularities[i] > 0, hoặc 1 nếu cả hai là 0
             if popularities[i] > 0:
                 comparison_matrix_popularity[i, j] = 1e9 # Giá trị rất lớn
             else:
                 comparison_matrix_popularity[i, j] = 1.0 # Coi như bằng nhau nếu cả 2 là 0
             print(f"Cảnh báo: Bài hát '{song_ids[j]}' có popularity = 0.")
        elif i == j:
            comparison_matrix_popularity[i, j] = 1.0
        else:
            # Tính tỷ lệ: popularity[i] / popularity[j]
            comparison_matrix_popularity[i, j] = float(popularities[i]) / popularities[j]

# --- Tính tổng các cột ---
column_sums_popularity = comparison_matrix_popularity.sum(axis=0)

# --- In ma trận và tổng cột theo định dạng ---
col_width = 12 # Điều chỉnh độ rộng cột
decimals_matrix = 3 # Số chữ số thập phân cho giá trị trong ma trận
decimals_sum = 5 # Số chữ số thập phân cho hàng tổng

print("\n--- Ma trận So Sánh Phương Án theo Tiêu chí: MỨC ĐỘ PHỔ BIẾN ---")
print("(So sánh dựa trên track_popularity: BH_i / BH_j)")

# In tiêu đề cột (BH1, BH2, ...)
header = f"{'':<{col_width}}" + "".join([f"{sid:<{col_width}}" for sid in song_ids])
print(header)
print("-" * len(header))

# In các hàng của ma trận
# Hàm định dạng để hiển thị phân số nếu có thể (tương tự trước)
def format_value(value, precision):
    if np.isclose(value, 1.0): return "1"
    if np.isclose(value, 1/2): return "1/2"
    if np.isclose(value, 1/3): return "1/3"
    if np.isclose(value, 1/4): return "1/4"
    if np.isclose(value, 1/5): return "1/5"
    if np.isclose(value, 1/6): return "1/6"
    if np.isclose(value, 1/7): return "1/7"
    if np.isclose(value, 1/8): return "1/8"
    if np.isclose(value, 1/9): return "1/9"
    # Kiểm tra số nguyên lớn hơn 1
    if value > 1 and np.isclose(value, round(value)):
        return str(int(round(value)))
    # Mặc định trả về float
    return f"{value:.{precision}f}"

for i in range(n_songs):
    row_str = f"{song_ids[i]:<{col_width}}" # Tên định danh hàng (BH1, ...)
    for j in range(n_songs):
        # Sử dụng hàm format_value để cố gắng hiển thị phân số
        formatted_num = format_value(comparison_matrix_popularity[i, j], decimals_matrix)
        row_str += f"{formatted_num:<{col_width}}" # Giá trị đã định dạng
    print(row_str)

# In dòng kẻ phân cách
print("-" * len(header))

# In hàng Sum
sum_row_str = f"{'Sum':<{col_width}}"
for total in column_sums_popularity:
    sum_row_str += f"{total:<{col_width}.{decimals_sum}f}"
print(sum_row_str)

# In ra tên bài hát tương ứng để tham khảo
print("\nÁnh xạ ID và Tên Bài Hát:")
for i in range(n_songs):
    print(f"{song_ids[i]}: {original_song_names[i]}")


--- Ma trận So Sánh Phương Án theo Tiêu chí: MỨC ĐỘ PHỔ BIẾN ---
(So sánh dựa trên track_popularity: BH_i / BH_j)
            BH1         BH2         BH3         BH4         
------------------------------------------------------------
BH1         1           0.985       0.943       1.100       
BH2         1.015       1           0.957       1.117       
BH3         1.061       1.045       1           1.167       
BH4         0.909       0.896       0.857       1           
------------------------------------------------------------
Sum         3.98485     3.92537     3.75714     4.38333     

Ánh xạ ID và Tên Bài Hát:
BH1: I Don't Care (with Justin Bieber) - Loud Luxury Remix
BH2: Memories - Dillon Francis Remix
BH3: All the Time - Don Diablo Remix
BH4: Call You Mine - Keanu Silva Remix


In [10]:
import numpy as np # Import lại phòng trường hợp cell mới chưa import

# --- Giả định các biến liên quan đến so sánh phương án theo popularity đã tồn tại ---
# comparison_matrix_popularity, column_sums_popularity, song_ids, n_songs

# Kiểm tra biến (tùy chọn)
required_vars_pop = ['comparison_matrix_popularity', 'column_sums_popularity', 'song_ids', 'n_songs']
if not all(v in globals() for v in required_vars_pop):
    print("Lỗi: Vui lòng chạy cell tính toán ma trận so sánh phương án theo 'Mức độ phổ biến' trước.")
else:
    # --- 1. Chuẩn hóa ma trận so sánh phương án (theo Popularity) ---
    # Chia từng phần tử cho tổng cột tương ứng
    print(comparison_matrix_popularity)
    print(column_sums_popularity)
    normalized_matrix_popularity = comparison_matrix_popularity / column_sums_popularity
    print(normalized_matrix_popularity)
    # --- 2. In ma trận đã chuẩn hóa ---
    col_width = 12 # Giữ nguyên hoặc điều chỉnh độ rộng cột
    decimal_places = 4 # Số chữ số thập phân theo yêu cầu

    print("\n--- Ma trận Phương Án Đã Chuẩn Hóa (theo Mức độ phổ biến) ---")
    print("(Giá trị ô / Tổng cột tương ứng)")

    # In tiêu đề cột (BH1, BH2, ...)
    header = f"{'':<{col_width}}" + "".join([f"{sid:<{col_width}}" for sid in song_ids])
    print(header)
    print("-" * len(header)) # Dòng kẻ ngang

    # In các hàng của ma trận chuẩn hóa
    for i in range(n_songs):
        row_str = f"{song_ids[i]:<{col_width}}" # Tên định danh hàng (BH1, ...)
        for j in range(n_songs):
            # Định dạng số float với số chữ số thập phân mong muốn
            formatted_num = f"{normalized_matrix_popularity[i, j]:.{decimal_places}f}"
            row_str += f"{formatted_num:<{col_width}}" # Giá trị đã định dạng
        print(row_str)

    # (Không cần in hàng SUM cho ma trận chuẩn hóa này)

    # Bạn có thể muốn lưu lại ma trận chuẩn hóa này
    # priority_vector_popularity = normalized_matrix_popularity.mean(axis=1) # Tính trọng số cục bộ ở bước sau

[[1.         0.98507463 0.94285714 1.1       ]
 [1.01515152 1.         0.95714286 1.11666667]
 [1.06060606 1.04477612 1.         1.16666667]
 [0.90909091 0.89552239 0.85714286 1.        ]]
[3.98484848 3.92537313 3.75714286 4.38333333]
[[0.25095057 0.25095057 0.25095057 0.25095057]
 [0.25475285 0.25475285 0.25475285 0.25475285]
 [0.2661597  0.2661597  0.2661597  0.2661597 ]
 [0.22813688 0.22813688 0.22813688 0.22813688]]

--- Ma trận Phương Án Đã Chuẩn Hóa (theo Mức độ phổ biến) ---
(Giá trị ô / Tổng cột tương ứng)
            BH1         BH2         BH3         BH4         
------------------------------------------------------------
BH1         0.2510      0.2510      0.2510      0.2510      
BH2         0.2548      0.2548      0.2548      0.2548      
BH3         0.2662      0.2662      0.2662      0.2662      
BH4         0.2281      0.2281      0.2281      0.2281      
